version: '3.8'

services:
  # Web服务器 (Apache + PHP)
  web:
    build: .
    container_name: cultivation_game_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      - db
    networks:
      - cultivation_network
    restart: unless-stopped

  # MySQL数据库
  db:
    image: mysql:8.0
    container_name: cultivation_game_db
    environment:
      MYSQL_ROOT_PASSWORD: cultivation_root_2024
      MYSQL_DATABASE: cultivation_game
      MYSQL_USER: cultivation_user
      MYSQL_PASSWORD: cultivation_pass_2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./api/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cultivation_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin (可选，用于数据库管理)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cultivation_game_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: cultivation_user
      PMA_PASSWORD: cultivation_pass_2024
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - cultivation_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  cultivation_network:
    driver: bridge
