version: '3.8'

# 使用Docker Hub镜像的docker-compose配置
# 使用方法: docker-compose -f docker-compose.hub.yml up -d

services:
  # Web服务器 (使用Docker Hub镜像)
  web:
    image: your-dockerhub-username/cultivation-game:latest
    container_name: cultivation_game_web
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=cultivation_game
      - DB_USER=cultivation_user
      - DB_PASS=cultivation_pass_2024
      - API_SECRET_KEY=cultivation_secret_key_2024_change_in_production
      - JWT_SECRET=cultivation_jwt_secret_2024_change_in_production
    depends_on:
      - db
    networks:
      - cultivation_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/test"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL数据库
  db:
    image: mysql:8.0
    container_name: cultivation_game_db
    environment:
      MYSQL_ROOT_PASSWORD: cultivation_root_2024
      MYSQL_DATABASE: cultivation_game
      MYSQL_USER: cultivation_user
      MYSQL_PASSWORD: cultivation_pass_2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # 如果需要初始化数据库，可以挂载SQL文件
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cultivation_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # phpMyAdmin (可选，用于数据库管理)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cultivation_game_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: cultivation_user
      PMA_PASSWORD: cultivation_pass_2024
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - cultivation_network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  cultivation_network:
    driver: bridge
